// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionNode_Bid_FullMethodName    = "/AuctionNode/Bid"
	AuctionNode_Result_FullMethodName = "/AuctionNode/Result"
)

// AuctionNodeClient is the client API for AuctionNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auction-node service. Clients may RPC-call bidding (TryBid),
// as well as query the state of the auction (TryResult)
type AuctionNodeClient interface {
	Bid(ctx context.Context, in *ProposedBid, opts ...grpc.CallOption) (*Acknowledgement, error)
	Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*Outcome, error)
}

type auctionNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionNodeClient(cc grpc.ClientConnInterface) AuctionNodeClient {
	return &auctionNodeClient{cc}
}

func (c *auctionNodeClient) Bid(ctx context.Context, in *ProposedBid, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, AuctionNode_Bid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionNodeClient) Result(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, AuctionNode_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionNodeServer is the server API for AuctionNode service.
// All implementations must embed UnimplementedAuctionNodeServer
// for forward compatibility.
//
// Auction-node service. Clients may RPC-call bidding (TryBid),
// as well as query the state of the auction (TryResult)
type AuctionNodeServer interface {
	Bid(context.Context, *ProposedBid) (*Acknowledgement, error)
	Result(context.Context, *ResultRequest) (*Outcome, error)
	mustEmbedUnimplementedAuctionNodeServer()
}

// UnimplementedAuctionNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionNodeServer struct{}

func (UnimplementedAuctionNodeServer) Bid(context.Context, *ProposedBid) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionNodeServer) Result(context.Context, *ResultRequest) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionNodeServer) mustEmbedUnimplementedAuctionNodeServer() {}
func (UnimplementedAuctionNodeServer) testEmbeddedByValue()                     {}

// UnsafeAuctionNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionNodeServer will
// result in compilation errors.
type UnsafeAuctionNodeServer interface {
	mustEmbedUnimplementedAuctionNodeServer()
}

func RegisterAuctionNodeServer(s grpc.ServiceRegistrar, srv AuctionNodeServer) {
	// If the following call pancis, it indicates UnimplementedAuctionNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionNode_ServiceDesc, srv)
}

func _AuctionNode_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposedBid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNode_Bid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServer).Bid(ctx, req.(*ProposedBid))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionNode_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionNodeServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionNode_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionNodeServer).Result(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionNode_ServiceDesc is the grpc.ServiceDesc for AuctionNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuctionNode",
	HandlerType: (*AuctionNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _AuctionNode_Bid_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _AuctionNode_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
