// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcknowledgementType int32

const (
	Acknowledgement_EXCEPTION AcknowledgementType = 0
	Acknowledgement_FAIL      AcknowledgementType = 1
	Acknowledgement_SUCCESS   AcknowledgementType = 2
)

// Enum value maps for AcknowledgementType.
var (
	AcknowledgementType_name = map[int32]string{
		0: "EXCEPTION",
		1: "FAIL",
		2: "SUCCESS",
	}
	AcknowledgementType_value = map[string]int32{
		"EXCEPTION": 0,
		"FAIL":      1,
		"SUCCESS":   2,
	}
)

func (x AcknowledgementType) Enum() *AcknowledgementType {
	p := new(AcknowledgementType)
	*p = x
	return p
}

func (x AcknowledgementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcknowledgementType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (AcknowledgementType) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x AcknowledgementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcknowledgementType.Descriptor instead.
func (AcknowledgementType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1, 0}
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BidAmount     int32                  `protobuf:"varint,2,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Bid) GetBidAmount() int32 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HighestBid    int32                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

type Outcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Outcome_HighestBid
	//	*Outcome_Result
	Type          isOutcome_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Outcome) GetType() isOutcome_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Outcome) GetHighestBid() int32 {
	if x != nil {
		if x, ok := x.Type.(*Outcome_HighestBid); ok {
			return x.HighestBid
		}
	}
	return 0
}

func (x *Outcome) GetResult() *Result {
	if x != nil {
		if x, ok := x.Type.(*Outcome_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isOutcome_Type interface {
	isOutcome_Type()
}

type Outcome_HighestBid struct {
	HighestBid int32 `protobuf:"varint,1,opt,name=highest_bid,json=highestBid,proto3,oneof"`
}

type Outcome_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*Outcome_HighestBid) isOutcome_Type() {}

func (*Outcome_Result) isOutcome_Type() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"A\n" +
	"\x03Bid\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x02 \x01(\x05R\tbidAmount\"?\n" +
	"\x0fAcknowledgement\",\n" +
	"\x04type\x12\r\n" +
	"\tEXCEPTION\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\"9\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x05R\n" +
	"highestBid\"W\n" +
	"\aOutcome\x12!\n" +
	"\vhighest_bid\x18\x01 \x01(\x05H\x00R\n" +
	"highestBid\x12!\n" +
	"\x06result\x18\x02 \x01(\v2\a.ResultH\x00R\x06resultB\x06\n" +
	"\x04type\"\a\n" +
	"\x05Empty2G\n" +
	"\x04Node\x12 \n" +
	"\x06TryBid\x12\x04.Bid\x1a\x10.Acknowledgement\x12\x1d\n" +
	"\tTryResult\x12\x06.Empty\x1a\b.Outcome2T\n" +
	"\aAuction\x12%\n" +
	"\vEvaluateBid\x12\x04.Bid\x1a\x10.Acknowledgement\x12\"\n" +
	"\x0eEvaluateResult\x12\x06.Empty\x1a\b.OutcomeB&Z$DistributedAuctionSystem/proto/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_goTypes = []any{
	(AcknowledgementType)(0), // 0: Acknowledgement.type
	(*Bid)(nil),              // 1: Bid
	(*Acknowledgement)(nil),  // 2: Acknowledgement
	(*Result)(nil),           // 3: Result
	(*Outcome)(nil),          // 4: Outcome
	(*Empty)(nil),            // 5: Empty
}
var file_proto_proto_depIdxs = []int32{
	3, // 0: Outcome.result:type_name -> Result
	1, // 1: Node.TryBid:input_type -> Bid
	5, // 2: Node.TryResult:input_type -> Empty
	1, // 3: Auction.EvaluateBid:input_type -> Bid
	5, // 4: Auction.EvaluateResult:input_type -> Empty
	2, // 5: Node.TryBid:output_type -> Acknowledgement
	4, // 6: Node.TryResult:output_type -> Outcome
	2, // 7: Auction.EvaluateBid:output_type -> Acknowledgement
	4, // 8: Auction.EvaluateResult:output_type -> Outcome
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	file_proto_proto_msgTypes[3].OneofWrappers = []any{
		(*Outcome_HighestBid)(nil),
		(*Outcome_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
